version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://developerDB:developerPass@dbPostgres/developer-concentration?schema=public"
    container_name: appConcentration
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: developerDB
      POSTGRES_PASSWORD: developerPass
      POSTGRES_DB: developer-concentration
    ports:
      - "5432:5432"
    container_name: dbPostgres
  prisma:
    build: .
    command: ["npx", "prisma", "migrate", "dev"]
    depends_on:
      - db